repos:
- repo: git://github.com/antonbabenko/pre-commit-terraform
  rev: v1.18.0
  hooks:
    - id: terraform_fmt
    # - id: terraform_docs <= Failed to work with Terraform 0.12+
- repo: git://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
    - id: check-merge-conflict